//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDBContainer : DbContext
    {
        public EntityDBContainer()
            : base("name=EntityDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Jogo> JogoSet { get; set; }
        public virtual DbSet<Deck> DeckSet { get; set; }
        public virtual DbSet<Carta> CartaSet { get; set; }
        public virtual DbSet<Torneio> TorneioSet { get; set; }
        public virtual DbSet<Equipa> EquipaSet { get; set; }
        public virtual DbSet<Jogador> JogadorSet { get; set; }
    }
}
