//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipa()
        {
            this.TorneioEquipa = new HashSet<TorneioEquipa>();
            this.Jogador = new HashSet<Jogador>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Avatar { get; set; }
        public int JogoEquipaId { get; set; }
        public int JogoEquipaId1 { get; set; }
    
        public virtual JogoEquipa JogoEquipa1 { get; set; }
        public virtual JogoEquipa JogoEquipa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TorneioEquipa> TorneioEquipa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jogador> Jogador { get; set; }
    }
}
