//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class JogoStandard : Jogo
    {
        public int JogadorId { get; set; }
        public int JogadorId1 { get; set; }
        public int TorneioStandardId { get; set; }
    
        public virtual Jogador Jogador1 { get; set; }
        public virtual Jogador Jogador2 { get; set; }
        public virtual TorneioStandard TorneioStandard { get; set; }
    }
}
